<template>
  <div>
    <Hero text1="About" />
    <div class="container mt-5">
      <div class="row d-flex">
        <div class="col-md-6">
          <img class="m-auto d-block w-75 rounded-5" src="/logo.jpg" alt="Früüters Logo" />
        </div>
        <div class="align-items-center d-flex col-md-6">
          <div class="container d-flex flex-column">
            <h3>Früüters</h3>
            <p class="lead">pioneering agricultural and horticultural business in Indonesia.</p>
            <p>
              Our mission is to advance the natural product industry in Indonesia, providing
              benefits to both farmers and the nation. Früüters.id serves as the base for marketing
              agricultural products in Indonesia, particularly in remote areas, contributing to the
              prosperity of local communities.
            </p>
            <p>
              We chose this business because Indonesia possesses abundant natural resources,
              especially high-quality fruits. Our country's diverse range of fruits, each with its
              own unique characteristics, is a valuable asset. Through Früüters.id, we plan to
              connect individuals or companies with the unique wealth of fruits in Indonesia for
              export to foreign countries.
            </p>
            <p>
              The profits generated by Früüters.id will be distributed, with 35% to investors, 8% to
              local farmers, 5% for social activities such as disaster relief and humanitarian aid,
              and the remaining 40% invested in the development of Früüters.id.
            </p>
          </div>
        </div>
      </div>
      <div class="row mt-5">
        <h3>Our members:</h3>
        <div class="col-md-4 mb-4">
          <div class="card">
            <div class="card-body">
              <div class="my-5 d-flex">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="60%"
                  height="60%"
                  fill="currentColor"
                  class="m-auto bi bi-person-circle"
                  viewBox="0 0 16 16"
                >
                  <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0" />
                  <path
                    fill-rule="evenodd"
                    d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"
                  />
                </svg>
              </div>
              <h5 class="card-title">Muh. Dziya Ramadhani Alvaro</h5>
              <p class="card-text">Ketua</p>
              <!-- Add other details as needed -->
            </div>
          </div>
        </div>

        <div class="col-md-4 mb-4">
          <div class="card">
            <div class="card-body">
              <div class="my-5 d-flex">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="60%"
                  height="60%"
                  fill="currentColor"
                  class="m-auto bi bi-person-circle"
                  viewBox="0 0 16 16"
                >
                  <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0" />
                  <path
                    fill-rule="evenodd"
                    d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"
                  />
                </svg>
              </div>
              <h5 class="card-title">M. Defrianza Nandana</h5>
              <p class="card-text">Anggota</p>
              <!-- Add other details as needed -->
            </div>
          </div>
        </div>
        <div class="col-md-4 mb-4">
          <div class="card">
            <div class="card-body">
              <div class="my-5 d-flex">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="60%"
                  height="60%"
                  fill="currentColor"
                  class="m-auto bi bi-person-circle"
                  viewBox="0 0 16 16"
                >
                  <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0" />
                  <path
                    fill-rule="evenodd"
                    d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"
                  />
                </svg>
              </div>
              <h5 class="card-title">Hanif Farhan Abdillah</h5>
              <p class="card-text">Anggota</p>
              <!-- Add other details as needed -->
            </div>
          </div>
        </div>
        <!-- Add more member cards as needed -->
      </div>
    </div>
  </div>
</template>

<script>
import Hero from '../components/Hero.vue'

export default {
  components: {
    Hero
  }
}
</script>

<style>
svg {
  color: tomato;
}
</style>
